// <auto-generated />
using System;
using Meyers.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Meyers.Infrastructure.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20250803140040_AddMenuTypeSupport")]
    partial class AddMenuTypeSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("Meyers.Core.Models.MenuEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MainDish")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuItems")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MenuTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MenuTypeId");

                    b.HasIndex("Date", "MenuTypeId")
                        .IsUnique();

                    b.ToTable("MenuEntries");
                });

            modelBuilder.Entity("Meyers.Core.Models.MenuType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("MenuTypes");
                });

            modelBuilder.Entity("Meyers.Core.Models.MenuEntry", b =>
                {
                    b.HasOne("Meyers.Core.Models.MenuType", "MenuType")
                        .WithMany("MenuEntries")
                        .HasForeignKey("MenuTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuType");
                });

            modelBuilder.Entity("Meyers.Core.Models.MenuType", b =>
                {
                    b.Navigation("MenuEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
