name: Deployment Check

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches: [ main ]
  workflow_dispatch:  # Allow manual trigger

jobs:
  check-migrations:
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Check migrations
      run: |
        cd Meyers.Web
        dotnet ef migrations list --no-build || echo "No migrations found"
        
  security-scan:
    runs-on: ubuntu-latest
    # Only run if CI workflow succeeded
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Run security scan
      run: |
        # Install security scanning tool
        dotnet tool install --global security-scan
        
        # Scan for known vulnerabilities
        dotnet list package --vulnerable --include-transitive || echo "No known vulnerabilities found"
        
    - name: Check Dockerfile best practices
      run: |
        # Check if Dockerfile follows best practices
        if grep -q "USER app" Dockerfile; then
          echo "✅ Dockerfile uses non-root user"
        else
          echo "⚠️ Dockerfile should use non-root user"
        fi
        
        if grep -q "EXPOSE 8080" Dockerfile; then
          echo "✅ Dockerfile exposes correct port"
        else
          echo "❌ Dockerfile should expose port 8080"
          exit 1
        fi

  deploy:
    runs-on: ubuntu-latest
    needs: [check-migrations, security-scan]
    # Only deploy if all checks pass and CI workflow succeeded
    if: ${{ success() && (github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch') }}
    
    steps:
    - name: Trigger Dokploy deployment
      run: |
        # Using the API to trigger deployment
        curl -X POST https://app.dokploy.com/api/application.deploy \
          -H "accept: application/json" \
          -H "Content-Type: application/json" \
          -H "x-api-key: ${{ secrets.DOKPLOY_API_KEY }}" \
          -d '{"applicationId": "IZA_MOq1GbodH1m719g_6"}' \
          --fail \
          --show-error \
          --silent \
          --output /dev/null
        echo "✅ Deployment triggered successfully"